### ISSUE TITLE
Страничка http://localhost:3000/patients Мало данных

### ISSUE THREAD

**Issue by team2soft** [team2soft/persey-front#23]
Мало данных в таблице
Следует расширить до 5 колонок
№ амбулаторной карты | Ф.И.О. | Телефон |  Дата рождения | Пол
Если человек является должником, тогда выделяем строку красным
Запрос на back возвращает 
{
	"message": "success",
	"data": [
		{
			"id" : 71,
			"fullname": "surname name patronimic",
			"birthday": "09.04.1986",
			"gender": "FEMALE",
			"cardNumber": 100500,
			"debtor": false,
			"phone": "(050)333-33-23"
		},
		{...},
		{...}
	]
}

**Comment by Adisey** [comment]
Дубль.
Будет решаться в рамках #19
