### ISSUE TITLE
http://localhost:3000/patients Изменить вид таблицы

### ISSUE THREAD

**Issue by team2soft** [team2soft/persey-front#25]
1. Заголовок таблицы выделить цветом
2. Фильтр поиска. Сделать поле для ввода текста. После ввода 3-х символов выводим результат.
3. Изменить внешний вид таблицы согласно макета 
4. Добавить возможность фильтрации по букве алфавита
5. Возле поля для поиска, добавить кнопку "Показать всех", которая будет очищать поле ввода

**Comment by team2soft** [comment]
![Картотека пациентов](https://user-images.githubusercontent.com/37050085/58475719-65b4db00-8157-11e9-9514-949d69f2a3a4.png)

**Comment by Adisey** [comment]
Дубль.
Будет выполнена в рамках #19
