### ISSUE TITLE
use url to save search params

### ISSUE THREAD

**Issue by Adisey** [team2soft/persey-front#26]
Использовать url для сохранения параметров поиска.
Позволит:
1. Возвращаться на страницу поиска, с сохранения условий поиска.
2. Обмениваться ссылками, с сохранения условий поиска.

**Comment by AVM82** [comment]
Немного изменить стилизацию страницы списка пациентов:
	a. Меню жирным
	b. Аватарку круглой
	c. Выровнять заголовок и поиск по левому краю таблицы

**Comment by Adisey** [comment]
Влили готовое в Develop
