### ISSUE TITLE
Patient visits

### ISSUE THREAD

**Issue by Adisey** [team2soft/persey-front#30]

**Comment by team2soft** [comment]
1. В мозиле заметно притормаживание при переключении вкладок "Карта пациента " и "История визитов"
2. остается возможность работать в соседней вкладке, даже если в текущей выполнен logout, а так же можно войти в систему нажав F5. Раз уж мы идем таким путем, то хотелось бы как в "Приват24". Если вышли в текущей вкладке, то в соседней на все запросы выдавать ошибку "Сервис временно не доступен", а при обновлении страницы выкидывать на форму логина.
3.  Поиск в мозиле и edge выдает ошибку
4. Ориентируемся на браузеры opera, mozilla, chrome. Версии текущие на 07/08/2019

**Comment by Adisey** [comment]
Именование полей
1.dispatcher, - не выводим
2."workType" -> Вид работ
3."workKind" -> Род работ
4."ambulance" -> Вызов скорой помощи (флаг, рисуем какой-то значок)
5."ambulanceDynamics" -> Флаг для динамики скорой помощи (флаг, рисуем какой-то значок)
6."whoSent"(Направивший врач) и "sentInstitution"(Направившее учреждение) пока не выводим
7. "diagnosis" -> Расшифровка кода диагноза по МКБ
8, "diagnosisText" -> Расшифровка кода диагноза по ICPC2
9."doctor" -> Доктор проводивший прием
10. "specialty" -> специальность доктора

**Comment by Adisey** [comment]
3, Поиск в мозиле и edge выдает ошибку
4. Ориентируемся на браузеры opera, mozilla, chrome. Версии текущие на 07/08/2019
Перенёс с #32

**Comment by Adisey** [comment]
>> В мозиле заметно притормаживание при переключении вкладок "Карта пациента " и "История визитов"
Не подтвердилось

**Comment by Adisey** [comment]
>> остается возможность работать в соседней вкладке, даже если в текущей выполнен logout, а так же можно войти в систему нажав F5. Раз уж мы идем таким путем, то хотелось бы как в "Приват24". Если вышли в текущей вкладке, то в соседней на все запросы выдавать ошибку "Сервис временно не доступен", а при обновлении страницы выкидывать на форму логина.

**Будет решено за счёт процедуры LogOut на БЭКе**

**Comment by Adisey** [comment]
#30 Complete Patient visits
